# Generated by Django 6.0 on 2025-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('hospital_request', 'Hospital Request'), ('request_status', 'Request Status'), ('low_blood', 'Low Blood')], max_length=50)),
                ('message', models.TextField()),
                ('hospital_name', models.CharField(blank=True, max_length=150, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
