# Generated by Django 6.0 on 2025-12-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('your_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('hospital_request', 'Hospital Request'), ('request_status', 'Request Status'), ('low_blood', 'Low Blood'), ('inventory_updated', 'Inventory Updated')], max_length=50),
        ),
    ]
